### ISSUE TITLE
a comedy of code errors!  🥺💔

### ISSUE THREAD

**Issue by alistkova** [Pepengu/ComputerShop#1]
Yo fam, I tried to run this code with 10 arguments, and now my terminal's throwing a tantrum! It’s like trying to fit a whole squad in a two-seater! 😤 Fix this before I start charging rent for all these extra arguments! 😂
Bruh, I pointed this code to a file that doesn't exist, and now it's acting like a heartbroken ex. Can we get some emotional support for this code? Maybe a 'File Not Found' therapy session? 🥺💔
So I tried using the scanner to read my grocery list, but it only wants to read lines about computers. Is it trying to tell me I need to upgrade my diet? 🍕🤖 #ComputerShopDiet
Every time I print the shop hours, it feels like I'm entering a time loop! Can we get a 'Back to the Future' feature in here? Like, what if I want to open the shop at 3 AM? ⏰🚀
My input is so spicy that the scanner just keeps running without stopping! It's like it's on an endless rollercoaster ride. Can we put some brakes on this thing? 🎢😱
Why does the shop close at 15:04? Is that some secret code for 'we're out of snacks'? Let’s make it 15:05 just to confuse everyone! 😂🍩

**Comment by Pepengu** [comment]
The project is open to contributions. Please provide pull request with fixes.
